-- Vighnaharta Mobile Shop Database Schema

-- 1. Create custom_skin_requests table
CREATE TABLE IF NOT EXISTS custom_skin_requests (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  device_type text NOT NULL,
  skin_type text NOT NULL,
  payment_type text NOT NULL,
  uploaded_design_url text,
  customization_notes text,
  customer_name text NOT NULL,
  customer_phone text,
  payment_status text DEFAULT 'Pending',
  order_status text DEFAULT 'Pending',
  admin_notes text,
  razorpay_payment_id text,
  razorpay_order_id text,
  razorpay_signature text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create products table (if missing in previous script)
CREATE TABLE IF NOT EXISTS products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  price numeric NOT NULL,
  category text,
  stock_status text,
  stock_quantity integer DEFAULT 0,
  description text,
  images jsonb,
  image text,
  featured boolean DEFAULT false,
  is_visible boolean DEFAULT true,
  rating numeric DEFAULT 5.0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create orders table for product reservations
CREATE TABLE IF NOT EXISTS orders (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  product_name text,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text,
  payment_type text NOT NULL, -- 'Full Payment' or 'Advance Payment'
  amount_paid numeric DEFAULT 0,
  order_status text DEFAULT 'Pending', -- Pending, Reserved, Processing, Ready for Pickup, Picked Up, Completed, Cancelled
  pickup_status text DEFAULT 'Pending',
  razorpay_payment_id text,
  razorpay_order_id text,
  razorpay_signature text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create categories table
CREATE TABLE IF NOT EXISTS categories (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL UNIQUE,
  image text,
  featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert initial categories
INSERT INTO categories (name) VALUES 
('Smartphones'), 
('Pre-Owned Phones'), 
('Mobile Skins'), 
('Laptop Skins'), 
('AirPods Skins'), 
('Accessories')
ON CONFLICT (name) DO NOTHING;

-- 5. Create settings table
CREATE TABLE IF NOT EXISTS settings (
  id text PRIMARY KEY,
  value jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default settings
INSERT INTO settings (id, value) VALUES 
('store_settings', '{"store_name": "Vighnaharta Mobile Shop", "whatsapp_number": "+917261934434", "instagram_link": "", "store_address": "Pune, Maharashtra", "google_maps_link": "", "business_hours": "10:00 AM - 9:00 PM"}')
ON CONFLICT (id) DO NOTHING;

-- 6. Row Level Security (RLS) Policies
-- Enable RLS on all tables
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_skin_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Products: Everyone can read visible products, only authenticated admins can write/update all
CREATE POLICY "Public read visible products" ON products FOR SELECT USING (is_visible = true OR auth.role() = 'authenticated');
CREATE POLICY "Admins can manage products" ON products FOR ALL USING (auth.role() = 'authenticated');

-- Categories: Everyone can read, admins can manage
CREATE POLICY "Public read categories" ON categories FOR SELECT USING (true);
CREATE POLICY "Admins can manage categories" ON categories FOR ALL USING (auth.role() = 'authenticated');

-- Orders & Requests: Public can insert (reserve), admins can read/update/delete
CREATE POLICY "Public insert orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins manage orders" ON orders FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Public insert skin requests" ON custom_skin_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins manage skin requests" ON custom_skin_requests FOR ALL USING (auth.role() = 'authenticated');

-- Settings: Public can read, admins can manage
CREATE POLICY "Public read settings" ON settings FOR SELECT USING (true);
CREATE POLICY "Admins manage settings" ON settings FOR ALL USING (auth.role() = 'authenticated');
