import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Check, Circle, Code2, GitCommit, Info, ShieldCheck, TriangleAlert } from "lucide-react";
import { loadData, DashboardData } from "./data/dataSource";
import "./styles/dashboard.css";

const statusLabel: Record<string, string> = { verified: "Verified", partial: "Partial", unverified: "Unverified", needs_review: "Needs review", exempt: "Exempt" };

export default function App() {
  const [data, setData] = useState<DashboardData | null>(null);
  useEffect(() => { let active = true; const refresh = () => loadData().then((next) => active && setData(next)); refresh(); const timer = window.setInterval(refresh, 3000); return () => { active = false; window.clearInterval(timer); }; }, []);
  if (!data) return <div className="loading-screen">Loading local project data…</div>;
  const { summary, blocks } = data;
  const critical = blocks.filter((block) => block.riskScore >= 60 && ["unverified", "needs_review", "partial"].includes(block.status)).sort((a, b) => b.riskScore - a.riskScore);
  const hasData = blocks.length > 0;
  return <div className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><ShieldCheck size={18} /></div><div><span className="brand-name">CodeIQ</span><span className="brand-tag">understanding dashboard</span></div></div><div className="workspace-pill"><span className="pulse" />{data.projectName}<span className="live-label">LOCAL</span></div></header>
    <main className="content"><section className="hero"><div><p className="kicker">PROJECT SIGNAL</p><h1>{data.projectName}</h1><p className="hero-copy">A quiet layer of confidence for the code you keep.</p></div><div className="last-sync"><span className="pulse" /> syncing from local store</div></section>
      {!hasData && <section className="empty-card"><Code2 size={30} /><h2>Start with understanding, not surveillance.</h2><p>AI can help you write the code. CodeIQ makes sure you understand the code you keep. Paste a meaningful block in VS Code and CodeIQ will surface a short, contextual checkpoint when it is useful.</p></section>}
      <section className="metric-grid"><article className="score-card"><div className="card-top"><span>Project understanding</span><Info size={15} /></div><div className="score-row"><div className="score">{summary.understandingPercent}<small>%</small></div><div className="score-ring" style={{ "--score": `${summary.understandingPercent * 3.6}deg` } as React.CSSProperties}><div>{summary.understandingPercent >= 70 ? "steady" : "building"}</div></div></div><div className="meter"><span style={{ width: `${summary.understandingPercent}%` }} /></div><p className="muted">Weighted by the risk of each tracked block.</p></article><article className="breakdown-card"><div className="card-top"><span>Verification mix</span><GitCommit size={15} /></div><div className="stacked-meter"><span className="verified" style={{ width: `${summary.verifiedPercent}%` }} /><span className="partial" style={{ width: `${Math.max(0, 100 - summary.verifiedPercent - summary.unverifiedPercent)}%` }} /><span className="unverified" style={{ width: `${summary.unverifiedPercent}%` }} /></div><div className="legend"><span><i className="dot verified" />Verified <b>{summary.verifiedPercent}%</b></span><span><i className="dot partial" />In progress <b>{Math.max(0, 100 - summary.verifiedPercent - summary.unverifiedPercent)}%</b></span><span><i className="dot unverified" />Needs review <b>{summary.unverifiedPercent}%</b></span></div><p className="muted">Status is a transparent signal, never a judgment.</p></article><article className="debt-card"><div className="card-top"><span>Understanding debt</span><ArrowUpRight size={15} /></div><div className="debt-number">{summary.understandingDebtPercent}<small>%</small></div><p>Code that is important enough to revisit, but has not had a clear explanation checkpoint yet.</p><a href="#critical">See what needs attention <ArrowUpRight size={14} /></a></article></section>
      <section className="two-col"><article className="panel" id="critical"><div className="panel-head"><div><p className="kicker">REVIEW QUEUE</p><h2>Critical blocks</h2></div><span className="count-badge">{summary.criticalUnverifiedCount} open</span></div>{critical.length ? <div className="block-list">{critical.map((block) => <div className="block-row" key={block.id}><div className="status-icon"><TriangleAlert size={16} /></div><div className="block-main"><strong>{block.filePath.split(/[\\/]/).pop()}</strong><span>Lines {block.startLine}–{block.endLine} · {block.language || "other"}</span><small>{block.riskReasons.slice(0, 2).join(" · ")}</small></div><div className="risk"><b>{block.riskScore}</b><span>risk</span></div></div>)}</div> : <div className="empty-panel"><Check size={18} /><p>No important blocks are waiting for review.</p></div>}</article><article className="panel"><div className="panel-head"><div><p className="kicker">ACTIVITY</p><h2>Recent checkpoints</h2></div><span className="quiet-label">local only</span></div>{summary.recentCheckpoints.length ? <div className="checkpoint-list">{summary.recentCheckpoints.map((checkpoint) => <div className="checkpoint-row" key={checkpoint.id}><StatusGlyph status={checkpoint.result.status} /><div><strong>{checkpoint.question.slice(0, 58)}{checkpoint.question.length > 58 ? "…" : ""}</strong><span>{new Date(checkpoint.createdAt).toLocaleString([], { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</span></div></div>)}</div> : <div className="empty-panel"><Circle size={18} /><p>Your first checkpoint will appear here.</p></div>}</article></section>
      <section className="panel language-panel"><div className="panel-head"><div><p className="kicker">COMPOSITION</p><h2>Language breakdown</h2></div><span className="quiet-label">tracked blocks</span></div><div className="language-bars">{Object.entries(summary.languageBreakdown).map(([language, count], index) => <div className="language-row" key={language}><span>{language}</span><div className="bar"><i style={{ width: `${Math.max(8, count / Math.max(...Object.values(summary.languageBreakdown)) * 100)}%`, background: ["#78e0b0", "#8ab4ff", "#d6a950", "#a99bf2"][index % 4] }} /></div><b>{count}</b></div>)}</div></section>
    </main><footer><span>CodeIQ by VERIQ</span><span>AI can help you write the code. CodeIQ makes sure you understand the code you keep.</span><span>privacy-first · no telemetry by default</span></footer>
  </div>;
}

function StatusGlyph({ status }: { status: string }) { return status === "verified" ? <span className="glyph verified"><Check size={14} /></span> : status === "partial" ? <span className="glyph partial"><TriangleAlert size={14} /></span> : <span className="glyph neutral"><Circle size={13} /></span>; }
